### ISSUE TITLE
Twilio API - Text

### ISSUE THREAD

**Issue by ha-x-3** [KBSwift/team-418#10]
Text is sent to user designated by Admin to remind that service is due.

**Comment by TrickyLiam** [comment]
Potentially add later?

- We can opt-in for texting in addition to emailing

**Comment by Tracy58468** [comment]
There appear to be no free SMS API providers. This is going to be a stretch goal, just because of potential costs involved.

**Comment by ha-x-3** [comment]
Removed from feature list during reallocation.
