### ISSUE TITLE
Google Search Functionality

### ISSUE THREAD

**Issue by ha-x-3** [KBSwift/team-418#8]
Utilize Amazon Price API to retrieve purchasing information for HVAC filter.

**Comment by TrickyLiam** [comment]
Have the Amazon database searchable by either keywords

**Comment by Tracy58468** [comment]
There look to be a few options. This one is free, but it might not be what we want. Others might require an Amazon Seller account ($39.99 a month), but I'm looking into that, still.

- [Product Advertising API 5.0](https://webservices.amazon.com/paapi5/documentation/)
- free (need Amazon Associate account)
- Product Advertising API sign up is available only to associates who have referred qualified sales and have been accepted into the program. (Might be a way around this, but I don't know, yet.) Brittney, if you are going to continue with this after Liftoff, it might be best if you were the one to sign up for this account.
- To sign up for an Amazon Associate account, we need a website. Kind of a chicken or egg scenario. "To begin the enrollment process, you must submit a complete and accurate Associates Program application. Your Site(s) must contain original content and be publicly available via the website address provided in the application. You must identify your Site(s) in your application. We will evaluate your application and notify you of its acceptance or rejection. Your Site will not be eligible for inclusion in the Associates Program, and you cannot include any Special Links or Product Advertising Content on it, if your Site is unsuitable."
- data includes items for sale, reviews, product promotions
- they suggest using this API for building your own web store to sell Amazon items
- The following are from the [license agreement](https://affiliate-program.amazon.com/help/operating/policies/#Associates%20Program%20IP%20License). We all should read this and be familiar with it.
- **Restrictions**:  "You will use Program Content solely in accordance with the terms of the [Agreement](https://affiliate-program.amazon.com/help/operating/agreement) and within the express scope of the license granted herein. Without limiting the foregoing, you will (a) use Program Content solely to send end users and sales to an Amazon Site and will not link any Program Content to, or in conjunction with any Program Content, direct traffic to any page of a site other than an Amazon Site (however, parts of your Site that are not closely associated with the Program Content may contain links to sites other than an Amazon Site) and (b) link each use of the Program Content solely to the related Product detail page or other relevant page of an Amazon Site and not to any other page."
- **Also**, "You will not use PA API, Data Feeds, or Product Advertising Content with any site or application, or in any other manner, that does not have the principal purpose of advertising and marketing an Amazon Site and driving sales of products and services on an Amazon Site."
- **Also**, "You will not, without our express prior written approval, use any Product Advertising Content on or in connection with any site or application designed or intended for use with a mobile phone or other handheld device. This prohibition will not apply to (1) any site that is not designed or intended for use with such devices but that may be accessible by such devices, such as a non-mobile-optimized site accessed via an internet browser on a tablet device; (2) an Approved Mobile Application as defined in the [ Mobile Application Policy](https://affiliate-program.amazon.com/help/operating/policies/#Associates%20Program%20Mobile%20Application%20Policy); or (3) any television set-top box (e.g., digital video recorders, cable or satellite boxes, streaming video players, blu-ray players, or dvd players) or Internet-enabled television (e.g., GoogleTV, Sony Bravia, Panasonic Viera Cast, or Vizio Internet Apps)."
