### ISSUE TITLE
Research e-mail API

### ISSUE THREAD

**Issue by ha-x-3** [KBSwift/team-418#9]
Email sent with Amazon link for purchase.

MailChimp?

**Comment by TrickyLiam** [comment]
Look into mailchimp? Can just send basic reminders based on time-interval (can get more specific if time/mailchimp allows)

**Comment by Tracy58468** [comment]
Yeah, I'm not sure Twilio has a free level, but I'll look into it.

**Comment by Tracy58468** [comment]
Yeah, SendGrid (Twilio) has a free level for e-mail. https://sendgrid.com/en-us/pricing

Twilio proper has no free SMS level:  https://www.twilio.com/en-us/sms/pricing/us

**Comment by Tracy58468** [comment]
Signed up with MailJet. Awaiting their decision on whether we can actually send e-mails with their service. I told them we'd be sending to our own e-mail addresses.

**Comment by ha-x-3** [comment]
Mailchimp or Twilio - send reminder to user at timed interval that is set by user
